
import { Player } from "@/types";

// Local players data for fallback
// Note: This is not the primary data source anymore, but kept as a fallback
export const players: Player[] = [
  // Group A - Russia
  {
    id: "rus1",
    name: "Igor Akinfeev",
    position: "Goalkeeper",
    club: "CSKA Moscow",
    country: "Russia",
    squad_number: 1,
    caps: 106,
    goals: 0,
    age: 32,
    height: 186,
    rating: 4,
    flagCode: "ru"
  },
  {
    id: "rus2",
    name: "Mario Fernandes",
    position: "Defender",
    club: "CSKA Moscow",
    country: "Russia",
    squad_number: 2,
    caps: 5,
    goals: 0,
    age: 27,
    height: 187,
    rating: 3,
    flagCode: "ru"
  },
  {
    id: "rus3",
    name: "Aleksandr Golovin",
    position: "Midfielder",
    club: "CSKA Moscow",
    country: "Russia",
    squad_number: 17,
    caps: 19,
    goals: 2,
    age: 22,
    height: 180,
    rating: 4,
    flagCode: "ru"
  },
  {
    id: "rus4",
    name: "Alan Dzagoev",
    position: "Midfielder",
    club: "CSKA Moscow",
    country: "Russia",
    squad_number: 10,
    caps: 57,
    goals: 9,
    age: 28,
    height: 179,
    rating: 4,
    flagCode: "ru"
  },
  {
    id: "rus5",
    name: "Artem Dzyuba",
    position: "Forward",
    club: "Arsenal Tula",
    country: "Russia",
    squad_number: 22,
    caps: 23,
    goals: 11,
    age: 29,
    height: 196,
    rating: 4,
    flagCode: "ru"
  },
  {
    id: "rus-coach",
    name: "Stanislav Cherchesov",
    position: "Coach",
    club: "Russia",
    country: "Russia",
    caps: 0,
    goals: 0,
    age: 54,
    flagCode: "ru"
  },
  
  // Group A - Saudi Arabia
  {
    id: "ksa1",
    name: "Mohammed Al-Owais",
    position: "Goalkeeper",
    club: "Al-Ahli",
    country: "Saudi Arabia",
    squad_number: 22,
    caps: 16,
    goals: 0,
    age: 26,
    height: 185,
    rating: 3,
    flagCode: "sa"
  },
  {
    id: "ksa2",
    name: "Osama Hawsawi",
    position: "Defender",
    club: "Al-Hilal",
    country: "Saudi Arabia",
    squad_number: 3,
    caps: 135,
    goals: 7,
    age: 34,
    height: 184,
    rating: 3,
    flagCode: "sa"
  },
  {
    id: "ksa3",
    name: "Salem Al-Dawsari",
    position: "Midfielder",
    club: "Al-Hilal",
    country: "Saudi Arabia",
    squad_number: 18,
    caps: 33,
    goals: 4,
    age: 26,
    height: 171,
    rating: 3,
    flagCode: "sa"
  },
  {
    id: "ksa4",
    name: "Fahad Al-Muwallad",
    position: "Forward",
    club: "Al-Ittihad",
    country: "Saudi Arabia",
    squad_number: 19,
    caps: 44,
    goals: 10,
    age: 23,
    height: 165,
    rating: 3,
    flagCode: "sa"
  },
  {
    id: "ksa5",
    name: "Mohammad Al-Sahlawi",
    position: "Forward",
    club: "Al-Nassr",
    country: "Saudi Arabia",
    squad_number: 10,
    caps: 40,
    goals: 28,
    age: 31,
    height: 180,
    rating: 3,
    flagCode: "sa"
  },
  {
    id: "ksa-coach",
    name: "Juan Antonio Pizzi",
    position: "Coach",
    club: "Saudi Arabia",
    country: "Saudi Arabia",
    caps: 0,
    goals: 0,
    age: 50,
    flagCode: "sa"
  },
  
  // Group A - Egypt
  {
    id: "egy1",
    name: "Mohamed Salah",
    position: "Forward",
    club: "Liverpool",
    country: "Egypt",
    squad_number: 10,
    caps: 57,
    goals: 33,
    age: 25,
    height: 175,
    rating: 5,
    flagCode: "eg"
  },
  {
    id: "egy2",
    name: "Essam El-Hadary",
    position: "Goalkeeper",
    club: "Al-Taawoun",
    country: "Egypt",
    squad_number: 1,
    caps: 158,
    goals: 0,
    age: 45,
    height: 188,
    rating: 3,
    flagCode: "eg"
  },
  {
    id: "egy3",
    name: "Ahmed Hegazi",
    position: "Defender",
    club: "West Bromwich Albion",
    country: "Egypt",
    squad_number: 6,
    caps: 45,
    goals: 1,
    age: 27,
    height: 195,
    rating: 3,
    flagCode: "eg"
  },
  {
    id: "egy4",
    name: "Ramadan Sobhi",
    position: "Midfielder",
    club: "Stoke City",
    country: "Egypt",
    squad_number: 22,
    caps: 23,
    goals: 1,
    age: 21,
    height: 183,
    rating: 3,
    flagCode: "eg"
  },
  {
    id: "egy5",
    name: "Mahmoud Trezeguet",
    position: "Midfielder",
    club: "Kasımpaşa",
    country: "Egypt",
    squad_number: 17,
    caps: 25,
    goals: 2,
    age: 23,
    height: 179,
    rating: 3,
    flagCode: "eg"
  },
  {
    id: "egy-coach",
    name: "Héctor Cúper",
    position: "Coach",
    club: "Egypt",
    country: "Egypt",
    caps: 0,
    goals: 0,
    age: 62,
    flagCode: "eg"
  },
  
  // Group A - Uruguay
  {
    id: "uru1",
    name: "Luis Suárez",
    position: "Forward",
    club: "Barcelona",
    country: "Uruguay",
    squad_number: 9,
    caps: 98,
    goals: 51,
    age: 31,
    height: 182,
    rating: 5,
    flagCode: "uy"
  },
  {
    id: "uru2",
    name: "Edinson Cavani",
    position: "Forward",
    club: "Paris Saint-Germain",
    country: "Uruguay",
    squad_number: 21,
    caps: 101,
    goals: 42,
    age: 31,
    height: 184,
    rating: 5,
    flagCode: "uy"
  },
  {
    id: "uru3",
    name: "Diego Godín",
    position: "Defender",
    club: "Atlético Madrid",
    country: "Uruguay",
    squad_number: 3,
    caps: 116,
    goals: 8,
    age: 32,
    height: 187,
    rating: 4,
    flagCode: "uy"
  },
  {
    id: "uru4",
    name: "Fernando Muslera",
    position: "Goalkeeper",
    club: "Galatasaray",
    country: "Uruguay",
    squad_number: 1,
    caps: 97,
    goals: 0,
    age: 31,
    height: 190,
    rating: 4,
    flagCode: "uy"
  },
  {
    id: "uru5",
    name: "José Giménez",
    position: "Defender",
    club: "Atlético Madrid",
    country: "Uruguay",
    squad_number: 2,
    caps: 42,
    goals: 5,
    age: 23,
    height: 185,
    rating: 4,
    flagCode: "uy"
  },
  {
    id: "uru-coach",
    name: "Óscar Tabárez",
    position: "Coach",
    club: "Uruguay",
    country: "Uruguay",
    caps: 0,
    goals: 0,
    age: 71,
    flagCode: "uy"
  },
  
  // Group B - Portugal
  {
    id: "8",
    name: "Cristiano Ronaldo",
    position: "Forward",
    club: "Real Madrid",
    country: "Portugal",
    squad_number: 7,
    caps: 150,
    goals: 81,
    age: 33,
    height: 187,
    rating: 5,
    flagCode: "pt"
  },
  {
    id: "por2",
    name: "Rui Patrício",
    position: "Goalkeeper",
    club: "Sporting CP",
    country: "Portugal",
    squad_number: 1,
    caps: 70,
    goals: 0,
    age: 30,
    height: 190,
    rating: 4,
    flagCode: "pt"
  },
  {
    id: "por3",
    name: "Pepe",
    position: "Defender",
    club: "Beşiktaş",
    country: "Portugal",
    squad_number: 3,
    caps: 99,
    goals: 7,
    age: 35,
    height: 188,
    rating: 4,
    flagCode: "pt"
  },
  {
    id: "por4",
    name: "Bernardo Silva",
    position: "Midfielder",
    club: "Manchester City",
    country: "Portugal",
    squad_number: 11,
    caps: 24,
    goals: 2,
    age: 23,
    height: 173,
    rating: 4,
    flagCode: "pt"
  },
  {
    id: "por5",
    name: "João Moutinho",
    position: "Midfielder",
    club: "Monaco",
    country: "Portugal",
    squad_number: 8,
    caps: 110,
    goals: 7,
    age: 31,
    height: 170,
    rating: 4,
    flagCode: "pt"
  },
  {
    id: "por-coach",
    name: "Fernando Santos",
    position: "Coach",
    club: "Portugal",
    country: "Portugal",
    caps: 0,
    goals: 0,
    age: 63,
    flagCode: "pt"
  },
  
  // Group B - Spain
  {
    id: "4",
    name: "Sergio Ramos",
    position: "Defender",
    club: "Real Madrid",
    country: "Spain",
    squad_number: 15,
    caps: 156,
    goals: 13,
    age: 32,
    height: 184,
    rating: 4,
    flagCode: "es"
  },
  {
    id: "esp2",
    name: "David de Gea",
    position: "Goalkeeper",
    club: "Manchester United",
    country: "Spain",
    squad_number: 1,
    caps: 29,
    goals: 0,
    age: 27,
    height: 192,
    rating: 5,
    flagCode: "es"
  },
  {
    id: "esp3",
    name: "Andrés Iniesta",
    position: "Midfielder",
    club: "Barcelona",
    country: "Spain",
    squad_number: 6,
    caps: 127,
    goals: 14,
    age: 34,
    height: 171,
    rating: 5,
    flagCode: "es"
  },
  {
    id: "esp4",
    name: "David Silva",
    position: "Midfielder",
    club: "Manchester City",
    country: "Spain",
    squad_number: 21,
    caps: 119,
    goals: 35,
    age: 32,
    height: 170,
    rating: 5,
    flagCode: "es"
  },
  {
    id: "esp5",
    name: "Diego Costa",
    position: "Forward",
    club: "Atlético Madrid",
    country: "Spain",
    squad_number: 19,
    caps: 18,
    goals: 7,
    age: 29,
    height: 188,
    rating: 4,
    flagCode: "es"
  },
  {
    id: "esp-coach",
    name: "Fernando Hierro",
    position: "Coach",
    club: "Spain",
    country: "Spain",
    caps: 0,
    goals: 0,
    age: 50,
    flagCode: "es"
  },
  
  // Group B - Morocco
  {
    id: "mar1",
    name: "Medhi Benatia",
    position: "Defender",
    club: "Juventus",
    country: "Morocco",
    squad_number: 5,
    caps: 58,
    goals: 2,
    age: 31,
    height: 190,
    rating: 4,
    flagCode: "ma"
  },
  {
    id: "mar2",
    name: "Hakim Ziyech",
    position: "Midfielder",
    club: "Ajax",
    country: "Morocco",
    squad_number: 7,
    caps: 17,
    goals: 9,
    age: 25,
    height: 181,
    rating: 4,
    flagCode: "ma"
  },
  {
    id: "mar3",
    name: "Younès Belhanda",
    position: "Midfielder",
    club: "Galatasaray",
    country: "Morocco",
    squad_number: 10,
    caps: 47,
    goals: 5,
    age: 28,
    height: 180,
    rating: 3,
    flagCode: "ma"
  },
  {
    id: "mar4",
    name: "Nordin Amrabat",
    position: "Midfielder",
    club: "Leganés",
    country: "Morocco",
    squad_number: 16,
    caps: 42,
    goals: 4,
    age: 31,
    height: 177,
    rating: 3,
    flagCode: "ma"
  },
  {
    id: "mar5",
    name: "Khalid Boutaïb",
    position: "Forward",
    club: "Yeni Malatyaspor",
    country: "Morocco",
    squad_number: 13,
    caps: 20,
    goals: 8,
    age: 31,
    height: 187,
    rating: 3,
    flagCode: "ma"
  },
  {
    id: "mar-coach",
    name: "Hervé Renard",
    position: "Coach",
    club: "Morocco",
    country: "Morocco",
    caps: 0,
    goals: 0,
    age: 49,
    flagCode: "ma"
  },
  
  // Group B - Iran
  {
    id: "irn1",
    name: "Alireza Beiranvand",
    position: "Goalkeeper",
    club: "Persepolis",
    country: "Iran",
    squad_number: 1,
    caps: 29,
    goals: 0,
    age: 25,
    height: 194,
    rating: 3,
    flagCode: "ir"
  },
  {
    id: "irn2",
    name: "Sardar Azmoun",
    position: "Forward",
    club: "Rubin Kazan",
    country: "Iran",
    squad_number: 20,
    caps: 33,
    goals: 23,
    age: 23,
    height: 186,
    rating: 3,
    flagCode: "ir"
  },
  {
    id: "irn3",
    name: "Ehsan Hajsafi",
    position: "Midfielder",
    club: "Olympiacos",
    country: "Iran",
    squad_number: 3,
    caps: 94,
    goals: 6,
    age: 28,
    height: 178,
    rating: 3,
    flagCode: "ir"
  },
  {
    id: "irn4",
    name: "Mehdi Taremi",
    position: "Forward",
    club: "Al-Gharafa",
    country: "Iran",
    squad_number: 17,
    caps: 20,
    goals: 11,
    age: 25,
    height: 187,
    rating: 3,
    flagCode: "ir"
  },
  {
    id: "irn5",
    name: "Reza Ghoochannejhad",
    position: "Forward",
    club: "Heerenveen",
    country: "Iran",
    squad_number: 16,
    caps: 43,
    goals: 17,
    age: 30,
    height: 180,
    rating: 3,
    flagCode: "ir"
  },
  {
    id: "irn-coach",
    name: "Carlos Queiroz",
    position: "Coach",
    club: "Iran",
    country: "Iran",
    caps: 0,
    goals: 0,
    age: 65,
    flagCode: "ir"
  },
  
  // Group C - France
  {
    id: "1",
    name: "Kylian Mbappé",
    position: "Forward",
    club: "Paris Saint-Germain",
    country: "France",
    squad_number: 10,
    caps: 45,
    goals: 19,
    age: 19,
    height: 178,
    rating: 5,
    flagCode: "fr"
  },
  {
    id: "9",
    name: "Antoine Griezmann",
    position: "Forward",
    club: "Atlético Madrid",
    country: "France",
    squad_number: 7,
    caps: 54,
    goals: 20,
    age: 27,
    height: 176,
    rating: 4,
    flagCode: "fr"
  },
  {
    id: "11",
    name: "N'Golo Kanté",
    position: "Midfielder",
    club: "Chelsea",
    country: "France",
    squad_number: 13,
    caps: 24,
    goals: 1,
    age: 27,
    height: 168,
    rating: 4,
    flagCode: "fr"
  },
  {
    id: "fra4",
    name: "Paul Pogba",
    position: "Midfielder",
    club: "Manchester United",
    country: "France",
    squad_number: 6,
    caps: 54,
    goals: 9,
    age: 25,
    height: 191,
    rating: 4,
    flagCode: "fr"
  },
  {
    id: "fra5",
    name: "Hugo Lloris",
    position: "Goalkeeper",
    club: "Tottenham Hotspur",
    country: "France",
    squad_number: 1,
    caps: 98,
    goals: 0,
    age: 31,
    height: 188,
    rating: 4,
    flagCode: "fr"
  },
  {
    id: "fra-coach",
    name: "Didier Deschamps",
    position: "Coach",
    club: "France",
    country: "France",
    caps: 0,
    goals: 0,
    age: 49,
    flagCode: "fr"
  },
  
  // Group C - Australia
  {
    id: "aus1",
    name: "Mile Jedinak",
    position: "Midfielder",
    club: "Aston Villa",
    country: "Australia",
    squad_number: 15,
    caps: 75,
    goals: 18,
    age: 33,
    height: 189,
    rating: 3,
    flagCode: "au"
  },
  {
    id: "aus2",
    name: "Mathew Ryan",
    position: "Goalkeeper",
    club: "Brighton & Hove Albion",
    country: "Australia",
    squad_number: 1,
    caps: 44,
    goals: 0,
    age: 26,
    height: 184,
    rating: 3,
    flagCode: "au"
  },
  {
    id: "aus3",
    name: "Tim Cahill",
    position: "Forward",
    club: "Millwall",
    country: "Australia",
    squad_number: 4,
    caps: 106,
    goals: 50,
    age: 38,
    height: 180,
    rating: 3,
    flagCode: "au"
  },
  {
    id: "aus4",
    name: "Aaron Mooy",
    position: "Midfielder",
    club: "Huddersfield Town",
    country: "Australia",
    squad_number: 13,
    caps: 35,
    goals: 5,
    age: 27,
    height: 174,
    rating: 3,
    flagCode: "au"
  },
  {
    id: "aus5",
    name: "Tomi Juric",
    position: "Forward",
    club: "Luzern",
    country: "Australia",
    squad_number: 9,
    caps: 35,
    goals: 8,
    age: 26,
    height: 189,
    rating: 3,
    flagCode: "au"
  },
  {
    id: "aus-coach",
    name: "Bert van Marwijk",
    position: "Coach",
    club: "Australia",
    country: "Australia",
    caps: 0,
    goals: 0,
    age: 66,
    flagCode: "au"
  },
  
  // Group C - Peru
  {
    id: "per1",
    name: "Paolo Guerrero",
    position: "Forward",
    club: "Flamengo",
    country: "Peru",
    squad_number: 9,
    caps: 86,
    goals: 34,
    age: 34,
    height: 185,
    rating: 3,
    flagCode: "pe"
  },
  {
    id: "per2",
    name: "Pedro Gallese",
    position: "Goalkeeper",
    club: "Veracruz",
    country: "Peru",
    squad_number: 1,
    caps: 38,
    goals: 0,
    age: 28,
    height: 189,
    rating: 3,
    flagCode: "pe"
  },
  {
    id: "per3",
    name: "Jefferson Farfán",
    position: "Forward",
    club: "Lokomotiv Moscow",
    country: "Peru",
    squad_number: 10,
    caps: 85,
    goals: 26,
    age: 33,
    height: 178,
    rating: 3,
    flagCode: "pe"
  },
  {
    id: "per4",
    name: "Christian Cueva",
    position: "Midfielder",
    club: "São Paulo",
    country: "Peru",
    squad_number: 8,
    caps: 49,
    goals: 9,
    age: 26,
    height: 169,
    rating: 3,
    flagCode: "pe"
  },
  {
    id: "per5",
    name: "André Carrillo",
    position: "Midfielder",
    club: "Watford",
    country: "Peru",
    squad_number: 18,
    caps: 55,
    goals: 5,
    age: 27,
    height: 178,
    rating: 3,
    flagCode: "pe"
  },
  {
    id: "per-coach",
    name: "Ricardo Gareca",
    position: "Coach",
    club: "Peru",
    country: "Peru",
    caps: 0,
    goals: 0,
    age: 60,
    flagCode: "pe"
  },
  
  // Group C - Denmark
  {
    id: "den1",
    name: "Christian Eriksen",
    position: "Midfielder",
    club: "Tottenham Hotspur",
    country: "Denmark",
    squad_number: 10,
    caps: 77,
    goals: 23,
    age: 26,
    height: 182,
    rating: 4,
    flagCode: "dk"
  },
  {
    id: "den2",
    name: "Kasper Schmeichel",
    position: "Goalkeeper",
    club: "Leicester City",
    country: "Denmark",
    squad_number: 1,
    caps: 34,
    goals: 0,
    age: 31,
    height: 189,
    rating: 4,
    flagCode: "dk"
  },
  {
    id: "den3",
    name: "Simon Kjær",
    position: "Defender",
    club: "Sevilla",
    country: "Denmark",
    squad_number: 4,
    caps: 78,
    goals: 3,
    age: 29,
    height: 189,
    rating: 3,
    flagCode: "dk"
  },
  {
    id: "den4",
    name: "Andreas Christensen",
    position: "Defender",
    club: "Chelsea",
    country: "Denmark",
    squad_number: 6,
    caps: 16,
    goals: 1,
    age: 22,
    height: 187,
    rating: 3,
    flagCode: "dk"
  },
  {
    id: "den5",
    name: "Pione Sisto",
    position: "Midfielder",
    club: "Celta Vigo",
    country: "Denmark",
    squad_number: 23,
    caps: 14,
    goals: 1,
    age: 23,
    height: 173,
    rating: 3,
    flagCode: "dk"
  },
  {
    id: "den-coach",
    name: "Åge Hareide",
    position: "Coach",
    club: "Denmark",
    country: "Denmark",
    caps: 0,
    goals: 0,
    age: 64,
    flagCode: "dk"
  },
  
  // Group D - Argentina
  {
    id: "6",
    name: "Lionel Messi",
    position: "Forward",
    club: "Barcelona",
    country: "Argentina",
    squad_number: 10,
    caps: 128,
    goals: 64,
    age: 30,
    height: 170,
    rating: 5,
    flagCode: "ar"
  },
  {
    id: "arg2",
    name: "Sergio Agüero",
    position: "Forward",
    club: "Manchester City",
    country: "Argentina",
    squad_number: 19,
    caps: 83,
    goals: 37,
    age: 30,
    height: 173,
    rating: 5,
    flagCode: "ar"
  },
  {
    id: "arg3",
    name: "Javier Mascherano",
    position: "Midfielder",
    club: "Hebei China Fortune",
    country: "Argentina",
    squad_number: 14,
    caps: 143,
    goals: 3,
    age: 34,
    height: 174,
    rating: 4,
    flagCode: "ar"
  },
  {
    id: "arg4",
    name: "Nicolás Otamendi",
    position: "Defender",
    club: "Manchester City",
    country: "Argentina",
    squad_number: 17,
    caps: 53,
    goals: 4,
    age: 30,
    height: 183,
    rating: 4,
    flagCode: "ar"
  },
  {
    id: "arg5",
    name: "Franco Armani",
    position: "Goalkeeper",
    club: "River Plate",
    country: "Argentina",
    squad_number: 12,
    caps: 0,
    goals: 0,
    age: 31,
    height: 189,
    rating: 3,
    flagCode: "ar"
  },
  {
    id: "arg-coach",
    name: "Jorge Sampaoli",
    position: "Coach",
    club: "Argentina",
    country: "Argentina",
    caps: 0,
    goals: 0,
    age: 58,
    flagCode: "ar"
  },
  
  // Group D - Iceland
  {
    id: "isl1",
    name: "Gylfi Sigurðsson",
    position: "Midfielder",
    club: "Everton",
    country: "Iceland",
    squad_number: 10,
    caps: 57,
    goals: 19,
    age: 28,
    height: 186,
    rating: 4,
    flagCode: "is"
  },
  {
    id: "isl2",
    name: "Hannes Þór Halldórsson",
    position: "Goalkeeper",
    club: "Randers",
    country: "Iceland",
    squad_number: 1,
    caps: 49,
    goals: 0,
    age: 34,
    height: 193,
    rating: 3,
    flagCode: "is"
  },
  {
    id: "isl3",
    name: "Aron Gunnarsson",
    position: "Midfielder",
    club: "Cardiff City",
    country: "Iceland",
    squad_number: 17,
    caps: 77,
    goals: 2,
    age: 29,
    height: 182,
    rating: 3,
    flagCode: "is"
  },
  {
    id: "isl4",
    name: "Birkir Bjarnason",
    position: "Midfielder",
    club: "Aston Villa",
    country: "Iceland",
    squad_number: 8,
    caps: 67,
    goals: 9,
    age: 30,
    height: 185,
    rating: 3,
    flagCode: "is"
  },
  {
    id: "isl5",
    name: "Alfreð Finnbogason",
    position: "Forward",
    club: "Augsburg",
    country: "Iceland",
    squad_number: 11,
    caps: 47,
    goals: 13,
    age: 29,
    height: 184,
    rating: 3,
    flagCode: "is"
  },
  {
    id: "isl-coach",
    name: "Heimir Hallgrímsson",
    position: "Coach",
    club: "Iceland",
    country: "Iceland",
    caps: 0,
    goals: 0,
    age: 51,
    flagCode: "is"
  },
  
  // Group D - Croatia
  {
    id: "cro1",
    name: "Luka Modrić",
    position: "Midfielder",
    club: "Real Madrid",
    country: "Croatia",
    squad_number: 10,
    caps: 106,
    goals: 13,
    age: 32,
    height: 172,
    rating: 5,
    flagCode: "hr"
  },
  {
    id: "cro2",
    name: "Ivan Rakitić",
    position: "Midfielder",
    club: "Barcelona",
    country: "Croatia",
    squad_number: 7,
    caps: 92,
    goals: 14,
    age: 30,
    height: 184,
    rating: 4,
    flagCode: "hr"
  },
  {
    id: "cro3",
    name: "Mario Mandžukić",
    position: "Forward",
    club: "Juventus",
    country: "Croatia",
    squad_number: 17,
    caps: 83,
    goals: 29,
    age: 32,
    height: 190,
    rating: 4,
    flagCode: "hr"
  },
  {
    id: "cro4",
    name: "Ivan Perišić",
    position: "Midfielder",
    club: "Inter Milan",
    country: "Croatia",
    squad_number: 4,
    caps: 69,
    goals: 18,
    age: 29,
    height: 186,
    rating: 4,
    flagCode: "hr"
  },
  {
    id: "cro5",
    name: "Danijel Subašić",
    position: "Goalkeeper",
    club: "Monaco",
    country: "Croatia",
    squad_number: 23,
    caps: 38,
    goals: 0,
    age: 33,
    height: 191,
    rating: 4,
    flagCode: "hr"
  },
  {
    id: "cro-coach",
    name: "Zlatko Dalić",
    position: "Coach",
    club: "Croatia",
    country: "Croatia",
    caps: 0,
    goals: 0,
    age: 51,
    flagCode: "hr"
  },
  
  // Group D - Nigeria
  {
    id: "nga1",
    name: "John Obi Mikel",
    position: "Midfielder",
    club: "Tianjin TEDA",
    country: "Nigeria",
    squad_number: 10,
    caps: 82,
    goals: 6,
    age: 31,
    height: 188,
    rating: 3,
    flagCode: "ng"
  },
  {
    id: "nga2",
    name: "Victor Moses",
    position: "Midfielder",
    club: "Chelsea",
    country: "Nigeria",
    squad_number: 11,
    caps: 34,
    goals: 11,
    age: 27,
    height: 177,
    rating: 3,
    flagCode: "ng"
  },
  {
    id: "nga3",
    name: "Alex Iwobi",
    position: "Forward",
    club: "Arsenal",
    country: "Nigeria",
    squad_number: 18,
    caps: 15,
    goals: 4,
    age: 22,
    height: 180,
    rating: 3,
    flagCode: "ng"
  },
  {
    id: "nga4",
    name: "Francis Uzoho",
    position: "Goalkeeper",
    club: "Deportivo La Coruña",
    country: "Nigeria",
    squad_number: 23,
    caps: 4,
    goals: 0,
    age: 19,
    height: 196,
    rating: 2,
    flagCode: "ng"
  },
  {
    id: "nga5",
    name: "Wilfred Ndidi",
    position: "Midfielder",
    club: "Leicester City",
    country: "Nigeria",
    squad_number: 4,
    caps: 17,
    goals: 0,
    age: 21,
    height: 186,
    rating: 3,
    flagCode: "ng"
  },
  {
    id: "nga-coach",
    name: "Gernot Rohr",
    position: "Coach",
    club: "Nigeria",
    country: "Nigeria",
    caps: 0,
    goals: 0,
    age: 64,
    flagCode: "ng"
  },
  
  // Group E - Brazil
  {
    id: "bra1",
    name: "Neymar",
    position: "Forward",
    club: "Paris Saint-Germain",
    country: "Brazil",
    squad_number: 10,
    caps: 85,
    goals: 55,
    age: 26,
    height: 175,
    rating: 5,
    flagCode: "br"
  },
  {
    id: "bra2",
    name: "Philippe Coutinho",
    position: "Midfielder",
    club: "Barcelona",
    country: "Brazil",
    squad_number: 11,
    caps: 37,
    goals: 10,
    age: 26,
    height: 172,
    rating: 5,
    flagCode: "br"
  },
  {
    id: "bra3",
    name: "Marcelo",
    position: "Defender",
    club: "Real Madrid",
    country: "Brazil",
    squad_number: 12,
    caps: 54,
    goals: 6,
    age: 30,
    height: 174,
    rating: 4,
    flagCode: "br"
  },
  {
    id: "bra4",
    name: "Gabriel Jesus",
    position: "Forward",
    club: "Manchester City",
    country: "Brazil",
    squad_number: 9,
    caps: 17,
    goals: 10,
    age: 21,
    height: 175,
    rating: 4,
    flagCode: "br"
  },
  {
    id: "bra5",
    name: "Alisson",
    position: "Goalkeeper",
    club: "Roma",
    country: "Brazil",
    squad_number: 1,
    caps: 25,
    goals: 0,
    age: 25,
    height: 193,
    rating: 4,
    flagCode: "br"
  },
  {
    id: "bra-coach",
    name: "Tite",
    position: "Coach",
    club: "Brazil",
    country: "Brazil",
    caps: 0,
    goals: 0,
    age: 57,
    flagCode: "br"
  },
  
  // Group E - Switzerland
  {
    id: "sui1",
    name: "Xherdan Shaqiri",
    position: "Midfielder",
    club: "Stoke City",
    country: "Switzerland",
    squad_number: 23,
    caps: 70,
    goals: 20,
    age: 26,
    height: 169,
    rating: 4,
    flagCode: "ch"
  },
  {
    id: "sui2",
    name: "Granit Xhaka",
    position: "Midfielder",
    club: "Arsenal",
    country: "Switzerland",
    squad_number: 10,
    caps: 61,
    goals: 9,
    age: 25,
    height: 185,
    rating: 4,
    flagCode: "ch"
  },
  {
    id: "sui3",
    name: "Yann Sommer",
    position: "Goalkeeper",
    club: "Borussia Mönchengladbach",
    country: "Switzerland",
    squad_number: 1,
    caps: 39,
    goals: 0,
    age: 29,
    height: 183,
    rating: 3,
    flagCode: "ch"
  },
  {
    id: "sui4",
    name: "Ricardo Rodríguez",
    position: "Defender",
    club: "Milan",
    country: "Switzerland",
    squad_number: 13,
    caps: 55,
    goals: 5,
    age: 25,
    height: 180,
    rating: 4,
    flagCode: "ch"
  },
  {
    id: "sui5",
    name: "Haris Seferović",
    position: "Forward",
    club: "Benfica",
    country: "Switzerland",
    squad_number: 9,
    caps: 55,
    goals: 13,
    age: 26,
    height: 189,
    rating: 3,
    flagCode: "ch"
  },
  {
    id: "sui-coach",
    name: "Vladimir Petković",
    position: "Coach",
    club: "Switzerland",
    country: "Switzerland",
    caps: 0,
    goals: 0,
    age: 54,
    flagCode: "ch"
  },
  
  // Group E - Costa Rica
  {
    id: "crc1",
    name: "Keylor Navas",
    position: "Goalkeeper",
    club: "Real Madrid",
    country: "Costa Rica",
    squad_number: 1,
    caps: 81,
    goals: 0,
    age: 31,
    height: 185,
    rating: 4,
    flagCode: "cr"
  },
  {
    id: "crc2",
    name: "Bryan Ruiz",
    position: "Midfielder",
    club: "Sporting CP",
    country: "Costa Rica",
    squad_number: 10,
    caps: 110,
    goals: 24,
    age: 32,
    height: 188,
    rating: 3,
    flagCode: "cr"
  },
  {
    id: "crc3",
    name: "Celso Borges",
    position: "Midfielder",
    club: "Deportivo La Coruña",
    country: "Costa Rica",
    squad_number: 5,
    caps: 112,
    goals: 21,
    age: 30,
    height: 184,
    rating: 3,
    flagCode: "cr"
  },
  {
    id: "crc4",
    name: "Joel Campbell",
    position: "Forward",
    club: "Real Betis",
    country: "Costa Rica",
    squad_number: 12,
    caps: 77,
    goals: 15,
    age: 25,
    height: 178,
    rating: 3,
    flagCode: "cr"
  },
  {
    id: "crc5",
    name: "Cristian Gamboa",
    position: "Defender",
    club: "Celtic",
    country: "Costa Rica",
    squad_number: 16,
    caps: 68,
    goals: 3,
    age: 28,
    height: 175,
    rating: 3,
    flagCode: "cr"
  },
  {
    id: "crc-coach",
    name: "Óscar Ramírez",
    position: "Coach",
    club: "Costa Rica",
    country: "Costa Rica",
    caps: 0,
    goals: 0,
    age: 53,
    flagCode: "cr"
  },
  
  // Group E - Serbia
  {
    id: "srb1",
    name: "Aleksandar Kolarov",
    position: "Defender",
    club: "Roma",
    country: "Serbia",
    squad_number: 11,
    caps: 77,
    goals: 10,
    age: 32,
    height: 187,
    rating: 4,
    flagCode: "rs"
  },
  {
    id: "srb2",
    name: "Nemanja Matić",
    position: "Midfielder",
    club: "Manchester United",
    country: "Serbia",
    squad_number: 21,
    caps: 40,
    goals: 2,
    age: 29,
    height: 194,
    rating: 4,
    flagCode: "rs"
  },
  {
    id: "srb3",
    name: "Dušan Tadić",
    position: "Midfielder",
    club: "Southampton",
    country: "Serbia",
    squad_number: 10,
    caps: 53,
    goals: 13,
    age: 29,
    height: 176,
    rating: 3,
    flagCode: "rs"
  },
  {
    id: "srb4",
    name: "Sergej Milinković-Savić",
    position: "Midfielder",
    club: "Lazio",
    country: "Serbia",
    squad_number: 20,
    caps: 4,
    goals: 0,
    age: 23,
    height: 191,
    rating: 4,
    flagCode: "rs"
  },
  {
    id: "srb5",
    name: "Aleksandar Mitrović",
    position: "Forward",
    club: "Fulham",
    country: "Serbia",
    squad_number: 9,
    caps: 38,
    goals: 16,
    age: 23,
    height: 187,
    rating: 3,
    flagCode: "rs"
  },
  {
    id: "srb-coach",
    name: "Mladen Krstajić",
    position: "Coach",
    club: "Serbia",
    country: "Serbia",
    caps: 0,
    goals: 0,
    age: 44,
    flagCode: "rs"
  },
  
  // Group F - Germany
  {
    id: "ger1",
    name: "Manuel Neuer",
    position: "Goalkeeper",
    club: "Bayern Munich",
    country: "Germany",
    squad_number: 1,
    caps: 76,
    goals: 0,
    age: 32,
    height: 193,
    rating: 5,
    flagCode: "de"
  }
];

