// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsipoigbzrechlqjokuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zaXBvaWdienJlY2hscWpva3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDA4ODEsImV4cCI6MjA1OTUxNjg4MX0.meHrk4ji9AvReG3URvrTzHUUNPHzuvDHy7ngeh0RtVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);